/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.innovative.telas;

import java.sql.*;
import br.com.innovative.dal.ModuloConexao;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author INNOVATIVE
 */
public class TelaLogin extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
        String sql = "select*from tbusuarios where login=? and senha=?";
        try {
            // As linhas abaixo preparam a consulta ao banco de Dados
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtUsuario.getText());
            pst.setString(2, txtSenha.getText());
            // A linha abaixo executa a query
            rs = pst.executeQuery();
            // Se existir usuário e senha correspondente
            if (rs.next()) {
                // A linha abaixo obtem o conteudo do campo perfil tbusuarios
                String perfil=rs.getString(7);
                // Ele mem mostra o conteúdo do campo perfil
                //System.out.println(perfil);
                // A estrutura abaixo faz o tratamento do perfil do usuário
                if(perfil.equals("admin")){
                TelaAdmin principal = new TelaAdmin();
                principal.setVisible(true);
                TelaAdmin.lblUsuario.setText(rs.getString(2));
                TelaAdmin.lblUsuario.setForeground(Color.black);
                // Fecha a janela de Login:
                this.dispose();
                // Fecha a conexão com o Banco de Dados
                conexao.close();
                }else if(perfil.equals("user")){
                    TelaUser principal = new TelaUser();
                    principal.setVisible(true);
                    // Fecha a janela de Login:
                    this.dispose();
                    // Fecha a conexão com o Banco de Dados
                    conexao.close();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou Senha inválido(s)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        conexao = ModuloConexao.conector();
        //Identifica erros na conexão
        //System.out.println(conexao);
        if (conexao != null) {
            status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/innovative/icones/Online.png")));
        } else {
            status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/innovative/icones/Offline.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fundo_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - INNOVATIVE");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/innovative/icones/x.png"))); // NOI18N
        btnFechar.setBorder(null);
        btnFechar.setContentAreaFilled(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.setFocusable(false);
        btnFechar.setHideActionText(true);
        btnFechar.setRequestFocusEnabled(false);
        btnFechar.setRolloverEnabled(false);
        btnFechar.setVerifyInputWhenFocusTarget(false);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 20, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setText("INNOVATIVE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/innovative/icones/Offline.png"))); // NOI18N
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtUsuario.setBorder(null);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 220, 40));

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSenha.setBorder(null);
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 220, 30));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/innovative/icones/Btn_Login.png"))); // NOI18N
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 330, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/innovative/imagensTelas/Loginn.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 370, -1));

        fundo_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/innovative/imagensTelas/Fundo_Login.png"))); // NOI18N
        getContentPane().add(fundo_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(384, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // A linha abaixo chama o método logar:
        logar();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // método fechar janela:
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel fundo_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel status;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
